---
title: "Analysis with Ensambles add more Ensambles"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Use all 14 traits

Compared to the competition: 

* Only a subset of columns is used
* The transmittance values are transformed to absorbance values.

```{r echo = FALSE, message=FALSE, warning= FALSE}
rm(list = ls())
set.seed(1979)
library(tidyverse)
library(dendextend)
library(glmnet) # for the ridge regression
library(pls)
library(ranger)
library(bartMachine)
library(e1071)
library(BKPC)
library(kernlab)
library(caret) # For ten fold crossvalidation



a <- read.csv("recleaneddataset1.csv") 


y_names <- c("kappa_casein",
"alpha_s2_casein",
"alpha_s1_casein",
"beta_casein",
"alpha_lactalbumin",
"beta_lactoglobulin_a",
"beta_lactoglobulin_b",
"Casein_micelle_size",
"Heat_stability",
"Native_pH",
"RCT",
"k20",
"a30",
"a60")

ys <- a %>% select(y_names)
x <- a[,60:590] 
matplot(t(x), type = "l", col = as.numeric(as.factor(a$Breed))+1)
matplot(t(x), type = "l", col = a$Farm+1)
# matplot(t(log(1/tr[,4:1060],10)), type = "l")
calcRMSE <- function(y, yhat){sqrt(mean((yhat - y)^2))}

#names(a)
id_te <- sample(nrow(x), 69)
ys_te <- ys[id_te,]
te <- x[id_te, ]
ys_tr <- ys[-id_te,]
tr <- x[-id_te, ]

me <- apply(tr,2,mean)
sd <- apply(tr,2,sd)

# pairs(log(ys)) # all non-normal
ys %>% pivot_longer(1:14, "key", "value") %>% ggplot(aes(x = log(value+1)))+ 
  geom_histogram()+facet_wrap(vars(key), scales = "free")

# matplot(t(tr), type = "l", col = 9, lty = 1)
# matplot(t(te), type = "l", col = 9, lty = 1)


# pairs(tr[,1:10])


tr <- scale(tr,me,sd)
te <- scale(te,me,sd)
# matplot(t(tr), type = "l", col = a$Farm[-id_te]+1, lty = 1)
# matplot(t(te), type = "l", col = as.numeric(as.factor(a$Breed[-id_te]))+1, lty = 1)


```


## Look for clusters in the training data

```{r echo = FALSE, message=FALSE, warning= FALSE}
D <- as.matrix(dist(tr,method="euclidean"))
# image(D)


h <- hclust(as.dist(D), method = "ward.D2")
d <- as.dendrogram(h)
# plot(d)

heatmap(D,
        Colv=as.dendrogram(h),     
        Rowv=as.dendrogram(h))


d2 <- color_branches(d,k=7, col=c(2,3,5,4, 6,7,8)) 
# auto-coloring 4 clusters of branches.
plot(d2)

# plot(reorder(d2, D, method = "OLO")) 

labl.Ave <- cutree(d2,7)
matplot(t(tr), type = "l", col = labl.Ave, lty = 1, ylab = "training data") # see the 7 clusters

# table(a$Farm[-id_te], labl.Ave)
# table(a$Breed[-id_te], labl.Ave)

#############################################################

```


## Look for clusters in the training data

```{r echo = FALSE, message=FALSE, warning= FALSE}
#############################################################

kfunc <-  rbfdot(sigma = 0.0005)
# kfunc <- laplacedot(sigma = 0.0001)
# kfunc <- anovadot(sigma = 1, degree = 1)
Ktrain <- kernelMatrix(kfunc, tr)
# image(Ktrain)

Ktest <- kernelMatrix(kfunc, te, tr)



kpcTrain <- kPCA(Ktrain)


# plot the data projection on the principal components

# pairs(kpcTrain$KPCs[ , 1 : 6], col = labl.Ave)

newdat <- cbind(log(ys_tr), kpcTrain$KPCs[ , 1 : 6], labl.Ave)

newdat <- newdat %>% as.data.frame() %>% na.omit() %>% mutate(labl.Ave = as.factor(labl.Ave))
# pairs(newdat[,1:20],  col = newdat[,21])
kpcTest <- predict(kpcTrain, Ktest)
# pairs(kpcTest[ , 1 : 6])
#############################################################

# correlation with responses

indexcor <- abs(cor(cbind(ys_tr,tr), use = "pairwise.complete.obs"))[1:14, -c(1:14)]
# matplot(t(indexcor), type = "l", col = 9, lty = 1)




# clustering the columns (variables) rather than observations
D2 <- as.matrix(1-abs(cor(tr)))

# image(D2)


h2<- hclust(as.dist(D2), method = "ward.D2")
dnew <- as.dendrogram(h2)
# plot(dnew)
# library(pheatmap)
# pheatmap(tr, cluster_cols = TRUE, clustering_distance_cols = "correlation",  cutree_cols  = 15)
heatmap(D2,
        Colv=as.dendrogram(h2),     
        Rowv=as.dendrogram(h2))


d2 <- color_branches(dnew,k=15, col = 2:16) 
# auto-coloring 4 clusters of branches.
 plot(d2)

# plot(reorder(d2, D2, method = "OLO")) 

labl.cols <- cutree(d2,15) # 15 variables
# matplot(t(tr), type = "l", col = labl.Ave, lty = 1)
# points(1:1060, rep(-5.8, 1060), col = labl.cols)

# image(t(indexcor))
# Pick 15 top features
nonz <- matrix(0,14,15)


for (j in unique(labl.cols)){
  for (i in 1:14){nonz[i, j] <- (which(indexcor[i,]==max(indexcor[i,labl.cols==j])))}
  }
  
  

# matplot(t(tr), type = "l", col = labl.Ave, lty = 1)
# abline(v = nonz[1,], col = 1:15) # pick values in a sensible region

# max(indexcor[1,])

# pairs(cbind(ys_tr[,1], tr[,nonz[1,]]), col = labl.Ave)
```


## Add more ensamble classifiers



* MA: model averaging
* Stack: regression
* Stack: non negative coefficients
* Stack: RF and all the predictors

```{r echo = FALSE, message=FALSE, warning= FALSE}

N <- 50
grid <- 10^seq(-3, 3, length = 100)
RMSEFULL <- vector(mode = "list", length = 14)
t1 <- vector(mode = "list", length = 14)
flds <- createFolds(1:200, k = 10, list = TRUE, returnTrain = FALSE)

  yind <- 1
for(yind in 1:14){
  if (yind ==8) dat <- cbind(log(ys_tr[,yind]), tr)else dat <- cbind(ys_tr[,yind], tr)
  
  dat <- as.data.frame(dat)
  p<- dat %>% ggplot(aes(x= V1)) + geom_histogram()
  print(p)
  dat <- dat %>% na.omit()
  
  nonzy <- nonz[yind,]
  ttt <- replicate(N, sample(nrow(dat), 200))
 
  
  RMSE <- matrix(0, N, 18)
  predictions.te <- matrix(0, nrow(dat)-200, 14)
  predictions.tv <- matrix(0, 200, 14)
 
  lmfitSG<- vector(mode = "list", length = N)
  lmfitSG2<- vector(mode = "list", length = N)
  rf.fitSG <- vector(mode = "list", length = N) 
  
  for (i in 1:N){
    

    dat.tr.full <- dat[ttt[,i],]
    dat.te <- dat[-ttt[,i],]
 
    for(l in 1:10){
        dat.tr <- dat.tr.full[-flds[[l]],]
        dat.tv <- dat.tr.full[flds[[l]],]
        
        j <- 1
        x <- model.matrix(V1 ~. , data = dat.tr)
        y1 <- dat.tr[,1]
        lasso.fit <- glmnet(x,y1,alpha=1, lambda = grid) # for lasso
        cv.out <- cv.glmnet(x,y1,alpha=1)
        # print(cv.out$lambda.min)
        
        lasso.fit <- glmnet(x,y1,alpha=1, 
                            lambda = cv.out$lambda.min)
        
        
        lasso.pred <- predict(lasso.fit, newx = model.matrix(V1 ~. , data = dat.tv))
        predictions.tv[flds[[l]] ,j] <- lasso.pred 
        j <- j + 1
        
        #############################################
        
        en.fit <- glmnet(x,y1,alpha=0.5, lambda = grid) # for lasso
        
        # plot(lasso.fit)
        
        cv.out <- cv.glmnet(x,y1,alpha=0.5)
        # print(cv.out$lambda.min)
        
        en.fit <- glmnet(x,y1,alpha=0.5, 
                         lambda = cv.out$lambda.min)
        
        
        en.pred <- predict(en.fit, newx = model.matrix(V1 ~. , data = dat.tv))
        predictions.tv[flds[[l]] ,j] <- en.pred 
        j <- j + 1
        
        
        # cbind(coef(lasso.fit), coef(en.fit))
        ####################################################
        
        pc <- prcomp(dat.tr[, 2:ncol(dat.tr)], scale = TRUE)
        
        lmfit<- lm(dat.tr[, 1]~pc$x[,1:5])
        
        x.tv <- predict(pc, dat.tv[, 2:ncol(dat.tr)])
        # pca.pred.poor <- as.matrix(cbind(rep(1, 200), pc$x[,1:5])) %*% as.matrix(lmfit$coef[1:6])
        pca.pred.poor.te <- as.matrix(cbind(rep(1, nrow(x.tv)), x.tv[,1:5])) %*% as.matrix(lmfit$coef[1:6])
        
        predictions.tv[flds[[l]] ,j] <- pca.pred.poor.te 
        j <- j + 1
        # plot(dat.tv[,1], pca.pred.poor.te, col = as.numeric(dat.tv$class), main = "PCA")
        # abline(a = 0, b = 1)
        
        #############################################################
        
        
        pls.fit <- plsr(V1 ~., data=dat.tr, scale= TRUE, validation = "CV")
        
        
        pls.pred <- predict(pls.fit, dat.tv[,-1], ncomp = 3)
        
        predictions.tv[flds[[l]] ,j] <- pls.pred 
        j <- j+ 1
        
        pls.pred <- predict(pls.fit, dat.tv[,-1], ncomp = 4)
        
        predictions.tv[flds[[l]] ,j] <- pls.pred 
        j <- j+ 1
        
        pls.pred <- predict(pls.fit, dat.tv[,-1], ncomp = 5)
        
        predictions.tv[flds[[l]] ,j] <- pls.pred 
        j <- j+ 1
        
        #############################################################
        
        lmfit <- lm(dat.tr[, 1]~ as.matrix(dat.tr[, nonzy+1]) )
        x <- model.matrix(V1 ~. , data = dat.tv[, c(1, nonzy+1)])
        pca.pred.poor.te <- x %*% as.matrix(lmfit$coef)
        
        
        predictions.tv[flds[[l]] ,j] <- pca.pred.poor.te 
        j <- j+ 1
        
        #############################################################
        
        
        
        rf.fit <- ranger(V1 ~ ., data = dat.tr, importance = "impurity")
        # plot(rf.fit$variable.importance)
        pred.rf <- predict(rf.fit , data = dat.tv)
        
        predictions.tv[flds[[l]] ,j] <- pred.rf$predictions 
        j <- j+1
        
        
        rf.fit <- ranger(V1 ~ ., data = dat.tr, importance = "impurity",regularization.factor = 0.2, regularization.usedepth=FALSE)
        # plot(rf.fit$variable.importance)
        pred.rf <- predict(rf.fit , data = dat.tv)
        
        predictions.tv[flds[[l]] ,j] <- pred.rf$predictions
        j <- j+1
        # plot(dat.tv[,1], pred.rf$predictions, col = as.numeric(dat.tv$class))
        # abline(0,1)
        
        
        
        bart_machine = bartMachine(as.data.frame(dat.tr[,-1]), dat.tr[,1], verbose = FALSE)
        # summary(bart_machine)
        pred.bart <- predict(bart_machine, as.data.frame(dat.tv[,-1]))
        predictions.tv[flds[[l]] ,j] <- pred.bart
        j <-j+1
        # plot(dat.tv[,1], pred.bart, col = as.numeric(dat.tv$class), main = "BART")
        # abline(0,1)
        
        
        Ktrain <- kernelMatrix(kfunc, as.matrix(dat.tr[,2:ncol(dat.tr)]))
        Kvalid <- kernelMatrix(kfunc, as.matrix(dat.tv[,2:ncol(dat.tr)]), as.matrix(dat.tr[,2:ncol(dat.tr)]))
        kpcTrain <- kPCA(Ktrain)
        
        
        # plot the data projection on the principal components
        
        # pairs(cbind(dat.tr[,1], kpcTrain$KPCs[ , 1 : 6]), col = dat.tr$class)
        kpcValid <- predict(kpcTrain, Kvalid)
        # pairs(kpcTest[ , 1 : 6], col = dat.tv$class)
        lmfit <- lm(dat.tr[, 1]~  kpcTrain$KPCs[ , 1 : 6] )
        
        pca.pred.poor.te <- cbind(rep(1,nrow(kpcValid)), kpcValid[ , 1 : 6]) %*% as.matrix(lmfit$coef)
        # plot(dat.tv[,1], pca.pred.poor.te , col = as.numeric(dat.tv$class), main = "KPCs")
        # abline(0,1)
        
        predictions.tv[flds[[l]] ,j] <- pca.pred.poor.te
        j <- j+ 1
        
        
        
        
        rf.fit <- ranger(y = dat.tr[, 1], x =  kpcTrain$KPCs[ , 1 : 6], importance = "impurity")
        # plot(rf.fit$variable.importance)
        pred.rf <- predict(rf.fit , data = kpcValid[ , 1 : 6])
        predictions.tv[flds[[l]] ,j] <- pred.rf$predictions
        j <- j+1
        
        
        
        rf.fit <- ranger(y = dat.tr[, 1], x =  Ktrain, importance = "impurity")
        # plot(rf.fit$variable.importance)
        pred.rf <- predict(rf.fit , data = Kvalid)
        predictions.tv[flds[[l]] ,j] <- pred.rf$predictions
        j <- j+1
        
        
        
        modelsvm <- svm(V1~.,dat.tr)
        
        #Predict using SVM regression
        predYsvm = predict(modelsvm, dat.tv)
        predictions.tv[flds[[l]] ,j] <- predYsvm
        j <- j+1
        # plot(dat.tv[,1], predYsvm,  main = "RF")
        # abline(0,1)
        
    
    }
    
     
    colnames(predictions.tv) <- c("lasso", "elastic net", "pca", "pls3", "pls4","pls5",  "LM+15", "RF", "RF+VS", "Bart", "kPCA","RF+kPCA", "RF+kernel", "svm")
    # pairs(cbind(dat.tr.full[,1], predictions.tv)) # correlated predictions
    
    
    
    lmfitSG[[i]]<- lm(dat.tr.full[,1]~predictions.tv - 1) 
    
    lmfitSG2[[i]] <- glmnet(predictions.tv,dat.tr.full[,1],alpha=1, lambda = 0, lower.limits = 0, intercept = FALSE) 
    # summary(  lmfit)
    
    rf.fitSG[[i]] <- ranger(y = dat.tr.full[, 1], x = cbind( predictions.tv, dat.tr.full[, -1]), importance = "impurity")
    
    
    ##-----------------------------------------------------------
    j <- 1
    x <- model.matrix(V1 ~. , data = dat.tr.full)
    y1 <- dat.tr.full[,1]
    lasso.fit <- glmnet(x,y1,alpha=1, lambda = grid) # for lasso
    cv.out <- cv.glmnet(x,y1,alpha=1)
    # print(cv.out$lambda.min)
    
    lasso.fit <- glmnet(x,y1,alpha=1, 
                        lambda = cv.out$lambda.min)
    
    
    lasso.pred <- predict(lasso.fit, newx = model.matrix(V1 ~. , data = dat.te))
    RMSE[i,j] <- calcRMSE(dat.te[,1], lasso.pred)
    predictions.te[,j] <- lasso.pred 
    j <- j + 1
    
    #############################################
    
    en.fit <- glmnet(x,y1,alpha=0.5, lambda = grid) # for lasso
    
    # plot(lasso.fit)
    
    cv.out <- cv.glmnet(x,y1,alpha=0.5)
    # print(cv.out$lambda.min)
    
    en.fit <- glmnet(x,y1,alpha=0.5, 
                     lambda = cv.out$lambda.min)
    
    
    en.pred <- predict(en.fit, newx = model.matrix(V1 ~. , data = dat.te))
    RMSE[i,j] <- calcRMSE(dat.te[,1], en.pred)
    predictions.te[,j] <- en.pred 
    j <- j + 1
    
    ####################################################
    
    pc <- prcomp(dat.tr.full[, 2:ncol(dat.tr.full)], scale = TRUE)
    
    lmfit<- lm(dat.tr.full[, 1]~pc$x[,1:5])
    
    x.te <- predict(pc, dat.te[, 2:ncol(dat.tr.full)])
    # pca.pred.poor <- as.matrix(cbind(rep(1, 200), pc$x[,1:5])) %*% as.matrix(lmfit$coef[1:6])
    pca.pred.poor.te <- as.matrix(cbind(rep(1, nrow(x.te)), x.te[,1:5])) %*% as.matrix(lmfit$coef[1:6])
    
    RMSE[i,j] <- calcRMSE(dat.te[,1], pca.pred.poor.te)
    predictions.te[,j] <- pca.pred.poor.te 
    j <- j + 1
    # plot(dat.te[,1], pca.pred.poor.te, col = as.numeric(dat.te$class), main = "PCA")
    # abline(a = 0, b = 1)
    
    #############################################################
    
    
    pls.fit <- plsr(V1 ~., data=dat.tr.full, scale= TRUE, validation = "CV")
    
    
    pls.pred <- predict(pls.fit, dat.te[,-1], ncomp = 3)
    
    RMSE[i,j] <- calcRMSE(dat.te[,1], pls.pred)
    predictions.te[,j] <- pls.pred 
    j <- j+ 1
    
    pls.pred <- predict(pls.fit, dat.te[,-1], ncomp = 4)
    
    RMSE[i,j] <- calcRMSE(dat.te[,1], pls.pred)
    predictions.te[,j] <- pls.pred 
    j <- j+ 1
    
    pls.pred <- predict(pls.fit, dat.te[,-1], ncomp = 5)
    
    RMSE[i,j] <- calcRMSE(dat.te[,1], pls.pred)
    predictions.te[,j] <- pls.pred 
    j <- j+ 1
    
    #############################################################
    
    lmfit <- lm(dat.tr.full[, 1]~ as.matrix(dat.tr.full[, nonzy+1]) )
    x <- model.matrix(V1 ~. , data = dat.te[, c(1, nonzy+1)])
    pca.pred.poor.te <- x %*% as.matrix(lmfit$coef)
    
    
    RMSE[i,j] <- calcRMSE(dat.te[,1], pca.pred.poor.te)
    predictions.te[,j] <- pca.pred.poor.te 
    j <- j+ 1
    
    #############################################################
    
    
    
    rf.fit <- ranger(V1 ~ ., data = dat.tr.full, importance = "impurity")
    # plot(rf.fit$variable.importance)
    pred.rf <- predict(rf.fit , data = dat.te)
    
    RMSE[i,j] <- calcRMSE(dat.te[,1], pred.rf$predictions)
    predictions.te[,j] <- pred.rf$predictions 
    j <- j+1
    
    
    rf.fit <- ranger(V1 ~ ., data = dat.tr.full, importance = "impurity",regularization.factor = 0.2, regularization.usedepth=FALSE)
    # plot(rf.fit$variable.importance)
    pred.rf <- predict(rf.fit , data = dat.te)
    
    RMSE[i,j] <- calcRMSE(dat.te[,1], pred.rf$predictions)
    predictions.te[,j] <- pred.rf$predictions
    j <- j+1
    # plot(dat.te[,1], pred.rf$predictions, col = as.numeric(dat.te$class))
    # abline(0,1)
    
    
    
    bart_machine = bartMachine(as.data.frame(dat.tr.full[,-1]), dat.tr.full[,1], verbose = FALSE)
    # summary(bart_machine)
    pred.bart <- predict(bart_machine, as.data.frame(dat.te[,-1]))
    RMSE[i,j] <- calcRMSE(dat.te[,1], pred.bart)
    predictions.te[,j] <- pred.bart
    j <-j+1
    # plot(dat.te[,1], pred.bart, col = as.numeric(dat.te$class), main = "BART")
    # abline(0,1)
    
    
    Ktrain <- kernelMatrix(kfunc, as.matrix(dat.tr.full[,2:ncol(dat.tr.full)]))
    Ktest <- kernelMatrix(kfunc, as.matrix(dat.te[,2:ncol(dat.tr.full)]), as.matrix(dat.tr.full[,2:ncol(dat.tr.full)]))
    kpcTrain <- kPCA(Ktrain)
    
    
    # plot the data projection on the principal components
    
    # pairs(cbind(dat.tr.full[,1], kpcTrain$KPCs[ , 1 : 6]), col = dat.tr.full$class)
    kpcTest <- predict(kpcTrain, Ktest)
    # pairs(kpcTest[ , 1 : 6], col = dat.te$class)
    lmfit <- lm(dat.tr.full[, 1]~  kpcTrain$KPCs[ , 1 : 6] )
    
    pca.pred.poor.te <- cbind(rep(1,nrow(kpcTest)), kpcTest[ , 1 : 6]) %*% as.matrix(lmfit$coef)
    # plot(dat.te[,1], pca.pred.poor.te , col = as.numeric(dat.te$class), main = "KPCs")
    # abline(0,1)
    
    
    RMSE[i,j] <- calcRMSE(dat.te[,1], pca.pred.poor.te)
    predictions.te[,j] <- pca.pred.poor.te
    j <- j+ 1
    
    
    
    
    rf.fit <- ranger(y = dat.tr.full[, 1], x =  kpcTrain$KPCs[ , 1 : 6], importance = "impurity")
    # plot(rf.fit$variable.importance)
    pred.rf <- predict(rf.fit , data = kpcTest[ , 1 : 6])
    
    RMSE[i,j] <- calcRMSE(dat.te[,1], pred.rf$predictions)
    predictions.te[,j] <- pred.rf$predictions
    j <- j+1
    
    
    
    rf.fit <- ranger(y = dat.tr.full[, 1], x =  Ktrain, importance = "impurity")
    # plot(rf.fit$variable.importance)
    pred.rf <- predict(rf.fit , data = Ktest)
    
    RMSE[i,j] <- calcRMSE(dat.te[,1], pred.rf$predictions)
    predictions.te[,j] <- pred.rf$predictions
    j <- j+1
    
    
    
    modelsvm <- svm(V1~.,dat.tr.full)
    
    #Predict using SVM regression
    predYsvm = predict(modelsvm, dat.te)
    RMSE[i,j] <- calcRMSE(dat.te[,1], predYsvm)
    predictions.te[,j] <- predYsvm
    j <- j+1
    # plot(dat.te[,1], predYsvm,  main = "RF")
    # abline(0,1)
    
    
    
    RMSE[i,j] <-  calcRMSE(dat.te[,1],   rowMeans(predictions.te[, 1:14]))
  }

    colnames(predictions.te) <- c("lasso", "elastic net", "pca", "pls3", "pls4","pls5",  "LM+15", "RF", "RF+VS", "Bart", "kPCA","RF+kPCA", "RF+kernel", "svm")
    # pairs(predictions.te)
    
     
  pred.stack <- as.matrix( predictions.te) %*% as.matrix(lmfitSG[[i]]$coef)
 
 pred.stack2 <- predict(lmfitSG2[[i]], predictions.te)
    

  pred.stackrf <- predict(rf.fitSG[[i]], data = cbind(predictions.te, dat.te[, -1]))$prediction

  # plot(pred.stack2, pred.stackrf)
# summary(  lmfit)
  

   RMSE[i,j+1] <- calcRMSE(dat.te[,1],  pred.stack)
   RMSE[i,j+2] <- calcRMSE(dat.te[,1],  pred.stack2)
   RMSE[i,j+3] <- calcRMSE(dat.te[,1],  pred.stackrf)
    
  }
    
  colnames(RMSE) <- c("lasso", "elastic net", "pca", "pls3", "pls4","pls5",  "LM+15", "RF", "RF+VS", "Bart", "kPCA","RF+kPCA", "RF+kernel", "svm", "ensamble MA",  "ensLM",  "ensNonNeg", "ensRF")
  RMSEFULL[[yind]] <- RMSE
  
  RMSE1 <- RMSE  %>%as.data.frame()%>% mutate(split = as.factor(1:N))%>% pivot_longer(1:18,"ALGORITHM")
  # RMSE1 %>% ggplot(aes(x = ALGORITHM, y = value)) + geom_boxplot()
  p1<- RMSE1 %>% group_by(ALGORITHM) %>% mutate(meanv = mean(value)) %>% ggplot(aes(x= ALGORITHM, y = value, color = split, group = split))+
    geom_point()+ geom_line() +geom_line(aes(x = ALGORITHM, y = meanv), col = 1)+ theme(legend.position = "none")+
    ylab("RMSE")+ ggtitle(names(ys_tr)[yind])+
    theme(axis.text.x=element_text(angle = 90, hjust = 0.5, vjust = 0.5))
  
  print(p1)
  
  t1[[yind]] <- RMSE1 %>% group_by(ALGORITHM) %>% summarise(meanv = mean(value), sdv=sd(value)) %>% arrange(desc(meanv))
  
}









```

```{r echo = FALSE}
t1
```

